# 请保存为UTF-8格式
server:
  port: 8001
spring:
  datasource:
    username: root
    password: abc123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/scs01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/scs02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
