server:
  port: 8002

mybatis:
  mapper-locations: classpath:mapper/*.xml               # mapper映射文件
  type-aliases-package: com.nuctech.springcloud.entities # 所有Entity别名类所在包
  configuration:
    map-underscore-to-camel-case: true                   # 开启驼峰命名
    cache-enabled: true                                  # 开启二级缓存

spring:
  application:
    name: scs-dept                                       # 应用名称（会注册进EurekaServer且全部字符串为大写）
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource         # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver           # mysql驱动包
    url: jdbc:mysql://localhost:3306/scs02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&verifyServerCertificate=false&useSSL=false
    username: root
    password: abc123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200

eureka:
  # 客户端注册进eureka服务列表内
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/ # [单机]
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # [集群]
  # 客户端服务实例配置
  instance:
    # 服务实例名称修改
    instance-id: scs-dept-8002
    # 访问路径显示IP地址
    prefer-ip-address: true

# Actuator Info信息配置
info:
  app.name: 微服务架构
  company.name: www.voishion.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
