server:
  port: 80

# Eureka客户端配置
eureka:
  client:
    # 自己不注册进Eureka
    register-with-eureka: false
    # Eureka服务地址列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ # [集群]